# Eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8013/eureka/"
## Spring DEBUG
logging:
  level:
    web: DEBUG
    org.springframework.context.annotation: DEBUG
    org.springframework.web: DEBUG
    com.albinus.netflix: TRACE
