server:
  port: 8082

spring:
  application:
    name: netflix-category-service
  profiles:
    default: dev
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
