version: '3.8'

# Define global variables using anchors
x-args:
  POM_VERSION: "1.0.0"
services:
  #  netflix-config
  netflix-config:
    image: netflix-config:latest
    container_name: netflix-config
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        SERVICE_DIR: netflix-config
        POM_VERSION: ${POM_VERSION}
    ports:
      - "8012:8012"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
#  # Spring Boot application services
#  netflix-user-service:
#    #  netflix-user-service
#    image: netflix-user-service:latest   # Use the name of your image or 'build' if building it in the compose file
#    build:
#      context: ./netflix-user-service               # Build the Dockerfile in the current directory
#      dockerfile: ./.docker/Dockerfile    # Dockerfile name if different
#    ports:
#      - "8081:8081"             # Map the application port
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/netflix_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=W6o6aOirRdDuxCk
#    networks:
#      - backend
#    depends_on:
#      - mysql                  # Wait for MySQL service before starting the Spring Boot app

  # MySQL service
  mysql:
    image: mysql:8.0
    container_name: mysql-netflix
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: W6o6aOirRdDuxCk
    ports:
      - "3306:3306"             # Expose MySQL port to localhost (if needed)
    volumes:
      - ./.database:/docker-entrypoint-initdb.d

# Define networks and volumes for the services
networks:
  backend:
    driver: bridge