pipeline {
	agent {
		label {
			label ''
			customWorkspace("workspace/${env.JOB_NAME}")
		}
	}

	options {
		timeout(time: 1, unit: 'HOURS')
		timestamps()
	}

	stages {
		stage('Initialisation') {
			steps {
				echo 'Initialisation of the project...'
			}
		}
		stage('Build') {
			steps {
				echo 'Building the project...'
			}
		}

		stage('Test') {
			steps {
				echo 'Running unit tests...'
			}
		}

		stage('Static Analysis') {
			steps {
				echo 'Running static code analysis...'
			}
		}

		stage('Package') {
			steps {
				echo 'Packaging the application...'
			}
		}

	}
	post {
		always {
			script{
				if (getContext(hudson.FilePath)) {
					// Suppression du workspace jenkins
					deleteDir()
					// Clean up the Docker system in order to tackle it.
					// The following command can be used to remove unused images only  (i.e. not referenced by any container) including dangling ones
					// You can use the -a flag (short for --all) as follows:
					sh("sudo sh -c 'yes | docker system prune -a'")
				}
			}
		}
	}
}
